<?php exit;
APP_PATH . 'plugin/well_cms/model/well_cms_admin.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_form.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_attach.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_thread.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_thread_flag.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_tag.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_post.func.php',
    APP_PATH.'plugin/well_cms/model/well_cms_misc_other.func.php',
    APP_PATH.'plugin/well_cms/model/well_cms_array.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_web.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_user.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_author.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_author_thread.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_source.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_source_thread.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_cache.func.php',
	APP_PATH.'plugin/well_cms/model/well_cms_cookie.func.php',
?>